# This is a basic workflow to help you get started with Actions

name: findEven

# Controls when the workflow will run
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  file_existence:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v1
        with:
          files: "FindEven.md"

      - name: File exists
        if: steps.check_files.outputs.files_exists == 'true'
        run: |
         echo | wc -l < FindEven.md
         if `echo | wc -l < FindEven.md` % 2 -eq 1; then
            exit 1
         else
            echo "even"
         fi
        
       
